@server = https://texai-miniature-succotash-x9vwjq4r6cvqj4-8080.preview.app.github.dev
@instumentos = {{server}}/api/instrumentos
@musicos = {{server}}/api/musicos
###
GET {{instumentos}}
###
POST {{instumentos}}
Content-Type: application/json

{
    "nombre": "Quena",
    "categoria": "Viento",
    "descripcion": "Tubo de madera con orificios"
}
###
POST {{musicos}}
Content-Type: application/json

{"nombre": "Otro Músico"}